# Based on https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml by BurntSushi (License MIT)

name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-release:
    name: build-release
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Get the release version from the tag
        shell: bash
        run: echo "RG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Compute node modules cache key
        id: nodeModulesCacheKey
        run: echo "value=$(node scripts/computeNodeModulesCacheKey.js)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cacheNodeModules-${{ steps.nodeModulesCacheKey.outputs.value }}
      - name: npm ci
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm run type-check
      - run: npm test
      - run: npm run lint
      - name: install playwright dependencies
        working-directory: ./packages/e2e
        run: npx playwright install chromium
        if: steps.npm-cache.outputs.cache-hit != 'true'
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - name: Run headless test
        run: npm run e2e:headless
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
      - run: node scripts/build.js
      - name: Build archive
        shell: bash
        run: |
          staging="eslint-${RG_VERSION}"
          mv "extension.tar.br" "$staging.tar.br"
          echo "ASSET=$staging.tar.br" >> $GITHUB_ENV

      - name: Create GitHub release
        run: gh release create "$RG_VERSION" "$ASSET" --repo "$GITHUB_REPOSITORY" --verify-tag --title "$RG_VERSION" --notes-from-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
